services:
  frontend:
    image: g0dd0r0/treffly-client:latest
    expose:
      - "80"
    restart: always
    networks:
      - app-network

  backend:
    image: m1ll3r1337/treffly-server:latest
    expose:
      - "8080"
    restart: always
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
