name: Backend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          DB_DRIVER: pgx
          DB_SOURCE: postgresql://postgres@localhost:5432/postgres?sslmode=disable&password=balls
          SERVER_ADDRESS: localhost:8080
          TOKEN_SYMMETRIC_KEY: 12345678901234567890123456789012
          ACCESS_TOKEN_DURATION: 15m
          REFRESH_TOKEN_DURATION: 168h
          ENVIRONMENT: production
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          goose -version

      - name: Run migrations
        run: goose -dir ./db/migration postgres "host=localhost dbname=postgres user=postgres password=secret sslmode=disable" up

      - name: Run tests
        run: go test -v ./...


  trigger-cd:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CD
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT  }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/TrefflyTeam/backend/actions/workflows/cd.yml/dispatches?ref=develop \
          -d '{"ref":"develop"}'